export const GET_TASKS_SUCCES = "GET_TASKS_SUCCES";
export const GET_TASKS_FAILED = "GET_TASKS_FAILED";
export const GET_TASKS_REQUESTED = "GET_TASKS_REQUESTED";

export const PUT_TASKS_SUCCES = "PUT_TASKS_SUCCES";
export const PUT_TASKS_FAILED = "PUT_TASKS_FAILED";
export const PUT_TASKS_REQUESTED = "PUT_TASKS_REQUESTED";

export const POST_TASKS_SUCCES = "POST_TASKS_SUCCES";
export const POST_TASKS_FAILED = "POST_TASKS_FAILED";
export const POST_TASKS_REQUESTED = "POST_TASKS_REQUESTED";

export const DELETE_TASKS_SUCCES = "DELETE_TASKS_SUCCES";
export const DELETE_TASKS_FAILED = "DELETE_TASKS_FAILED";
export const DELETE_TASKS_REQUESTED = "DELETE_TASKS_REQUESTED";
